### ISSUE TITLE
Option to store all songs history (file append) not just latest, in the output textfile, and to save the full datetime time-started string with %t% (or some other option)

### ISSUE THREAD

**Issue by jevanpipitone** [Wykks/Untamed-Now-Playing-Next#100]
See attachment for changes, however, you might be able to do this in a better way that allows it to be an option rather than "always" doing it
[modifications.zip](https://github.com/Wykks/Untamed-Now-Playing-Next/files/310774/modifications.zip)

**Comment by Wykks** [comment]
Uh, that's not a very convenient way to send me your modifications...

Anyway, I'll review then include your work as soon as possible, thanks !
