### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Exionfatalis** [Wykks/Untamed-Now-Playing-Next#104]
I have been trying to get UNP to save the txt file but I keep getting the "Error: Unable to write to save directory".

**Comment by Wykks** [comment]
Hi !

Which version of Firefox are you using ? On which OS ? Have you tried with others directory ?

**Comment by Exionfatalis** [comment]
My Os is win 10, and the version of Firefox is 48.0.

**Comment by Wykks** [comment]
Just tested on win 10 with FF 48.0 it works fine.
Double check if FF can actually write in your directory
