### ISSUE TITLE
site support for di.fm partner sites (radiotunes.com etc)

### ISSUE THREAD

**Issue by th2pun1sh3r** [Wykks/Untamed-Now-Playing-Next#111]
hey guys, sorry if this is the wrong place for this (totally new to github etc) if it is feel free to delete it.

so everything works great with the firefox extension and it gets the song names for obs on DI.FM however some of the di.fm owned sites that use different names are not programmed in. For example I listen to smooth jazz a lot on stream on this site http://www.radiotunes.com/smoothjazz (which uses the same username:PW as the di.fm account) but the song tracker can't pick this up.

Is there a way this could be added

Thank you for your time

-Paul

**Comment by Senpos** [comment]
**th2pun1sh3r**, sites probably differs from each other, so i Assume there are no single rule to make them all to work with one fix, but you can open issues for sites which you need.

**Comment by th2pun1sh3r** [comment]
ahh yeah just the radiotunes site should be good I mainly listen to jazz on there thank you

**Comment by Wykks** [comment]
Thanks Senpos !
