### ISSUE TITLE
vk.com broken since new design

### ISSUE THREAD

**Issue by Tander** [Wykks/Untamed-Now-Playing-Next#113]
vk.com broken since new design.
Please fix this and thanks for nice addon.

**Comment by Senpos** [comment]
@Tander 
This is already fixed in #106. Changes are already merged, but not actually in latest official build. 
You can build latest version from git by your own or wait for the official release.

**Comment by Tander** [comment]
Thanks, latest version is working. But firefox yelling that this .xpi not signed. It's okay to **disablexpinstall.signatures.required** by now, but mozilla want to remove this option soon. Hope you can update official release soon.

**Comment by Senpos** [comment]
@Tander It is easy to sign extension by you own. 
If you understand russian language - follow steps from this article: https://geektimes.ru/post/279294/
If not, let me know and i will sign it for you.

**Comment by Wykks** [comment]
Thanks Senpos :)
I'll do a release this week-end
