### ISSUE TITLE
Problem with Options

### ISSUE THREAD

**Issue by Megxx** [Wykks/Untamed-Now-Playing-Next#116]
My Browser dont open the options. It shows {{Version}}. When i click on {{Version}}, it shows me the url: resource://jid1-ccxbupa5pamtyw-at-jetpack/data/common/options/index.html#/about. I dont know whats happening. Browser Mozilla 48.0.2 Win7 64 Bit Untamed Version 3.5. All Browser Addons disabled except Untamed-Now-Playing-Next. What can i do ?

**Comment by Wykks** [comment]
Hi !

I'll remove angularjs in the next version.

It should fix your issue :)

**Comment by Megxx** [comment]
Hi,

thanks for your reply.  I will wait.

Thanks a lot. :)


Am 19.09.2016 um 11:18 schrieb Wykks:

**Comment by Wykks** [comment]
Should be fine now !
