### ISSUE TITLE
[plex] text file not auto updating 

### ISSUE THREAD

**Issue by Gamerbiomek2** [Wykks/Untamed-Now-Playing-Next#117]
everytime I change to a different artist on plex, non of the text is updated I have to reopen the link from the site features and restart the song
any fix would help

**Comment by Wykks** [comment]
Hi !

Sorry about that, I don't have access to plex. @exofudge added this (https://github.com/Wykks/Untamed-Now-Playing-Next/issues/96)
Until I, someday, have access to a plex instance, I don't plan to fix this, sorry :/

Any help is welcome !

**Comment by Senpos** [comment]
#169 should fix this for the newest version of Plex.
Details: https://github.com/Wykks/Untamed-Now-Playing-Next/issues/163#issuecomment-337485206
