### ISSUE TITLE
Option to add Space after music name

### ISSUE THREAD

**Issue by SaadeMotion** [Wykks/Untamed-Now-Playing-Next#121]
Hello! i'm using this plugin with OBS.

But with option "scroll" the last character joins with the first, because music name is scrolling, can u add a option to add space, or add space by default after last character? 

![screenshot at nov 04 19-19-11](https://cloud.githubusercontent.com/assets/14329460/20022894/d5dd0e4a-a2c3-11e6-843f-819aa67f9d50.png)

**Comment by Wykks** [comment]
Hi !
You can already do that
In the "Plain text now playing format" option, click on the '!' button :)
