### ISSUE TITLE
New Pandora Version broke plugin functionality

### ISSUE THREAD

**Issue by mixartist** [Wykks/Untamed-Now-Playing-Next#122]
I'm going to guess that the new update to the web playing broke the functionality, and you're probably already aware, but thought I'd give a heads up anyways.  Thanks for the great plugin!  It's been working perfectly for months.

**Comment by Wykks** [comment]
Hi !

Thanks for the info, I can't use pandora in my country, so, no I wasn't aware of that ! :D 

Can't say when I'll release the next version since I'm working on a major rewrite with limited time (progress here : https://github.com/Wykks/Untamed-Now-Playing-Next/tree/test_preact)

**Comment by Senpos** [comment]
@mixartist How can i turn on the new player? I'm testing free web version now and all seems to work properly.

**Comment by starhel** [comment]
It's working for me as well. There's probably no bug.

**Comment by Wykks** [comment]
Thanks for the feedback

So, I guess I can close this, for now
