### ISSUE TITLE
Include seconds in time_started?

### ISSUE THREAD

**Issue by DoctaEpic** [Wykks/Untamed-Now-Playing-Next#123]
I know this is a little nit picky, but it would help creating a song duration/progress bar. I'm trying to create a rainmeter skin for the plugin that uses a progress bar for each song, but without seconds the duration can vary wildly from the actual time.

**Comment by Wykks** [comment]
Hi !
Sure no problem; will do !

(I will *hopefully* release the next version this week-end; I have less time than expected for the rewrite...)

**Comment by DoctaEpic** [comment]
Thanks so much!
