### ISSUE TITLE
Getting UNP Mozilla reviewed version

### ISSUE THREAD

**Issue by DezZigeR** [Wykks/Untamed-Now-Playing-Next#131]
Hi there Wykks, thx for super fast response and dev about adding zvooq.com
but now i have trouble to install 4.1 version of UMP. Mozilla says its nor reviewed and did not allow me to install it.

google says i can try Firefox ESR / Developer Edition / Nightly... but looks like it needs some additional knowledge.

I really like you program cuz its simple to use and works just fine.

Can you tell when new Mozilla reviewed version will come?

**Comment by Senpos** [comment]
I hope, @Wykks will not mind, if i will post [ signed by myself git version of extension](https://drive.google.com/uc?id=0B6HBCntn0EZReTNsNG9Rcko5Mzg). But consider, it is not official build and will never be updated, so once official extension will be up-to-date on [Mozilla's Addons page](https://addons.mozilla.org/en-US/firefox/addon/untamed-now-playing/), make sure you will uninstall unofficial one and get official.

**Comment by DezZigeR** [comment]
Спасибо, Жень!

**Comment by Wykks** [comment]
:+1: 
I'll release the next version this week probably

**Comment by Wykks** [comment]
Still waiting mozilla review for version 4.2.0.. (current pos: 96/205)

**Comment by Wykks** [comment]
4.2.1 is finally out
