### ISSUE TITLE
no album art with plex.tv

### ISSUE THREAD

**Issue by Gamerbiomek2** [Wykks/Untamed-Now-Playing-Next#138]
I was wandering if you could try to get the album art, if I start streaming again soon, my viewers will want to know what album the song is from

**Comment by Senpos** [comment]
@Gamerbiomek2 
Does it work for you now? 
Related issues: #117 #139 #137

**Comment by Senpos** [comment]
Due to #169 album art will no longer be avaliable till someone will find out how to make it work.
