### ISSUE TITLE
xpi needs signing

### ISSUE THREAD

**Issue by Gamerbiomek2** [Wykks/Untamed-Now-Playing-Next#141]
I can't install the 4.2 add-on manually with out it being signed

**Comment by Wykks** [comment]
I'm waiting for Mozilla to sign the version 4.2 (since 27 days...)
UNP is currently 52 of 218 in the queue

**Comment by Gamerbiomek2** [comment]
ok thanks

**Comment by Wykks** [comment]
Still waiting... 17 of 290
