### ISSUE TITLE
cannot open options

### ISSUE THREAD

**Issue by ErisHime** [Wykks/Untamed-Now-Playing-Next#144]
This used to work great for me, then would quit updating the song being played, and now when I try to access the options, it just sends me to a blank page... resource://jid1-ccxbupa5pamtyw-at-jetpack/data/common/options/index.html to be exact. Maybe it's because I'm using Mozilla? Is this only updated for use with Chrome now? I'd like to keep using this for my stream since most of the music I use is on soundcloud and this is compatible with soundcloud.

**Comment by Wykks** [comment]
Hum that's weird. And no it's not working anymore with Chrome.
Which version of Firefox & UNP are you using ?

**Comment by IronPhoenixAshe** [comment]
Hi, I know this issue is over a month old but I am having the same one. I click the options link and I am sent to a blank website. I am using Firefox 54.0, UNP 4.2.1 and Mac OsX 10.11.6

Any help at all with this would be greatly appreciated.

**Comment by Gamerbiomek2** [comment]
same, broken on latest Firefox :(

**Comment by Wykks** [comment]
Will try to update this week (for the last time probably...)

**Comment by Gamerbiomek2** [comment]
options works now 👍
