### ISSUE TITLE
Unable to read soundcloud songs?

### ISSUE THREAD

**Issue by Candy-Sama** [Wykks/Untamed-Now-Playing-Next#146]
Hi Devs!

I'm having issues with reading my soundcloud songs, please help! ;~;

Here's a screenshot that shows up in the btm right when a new song is played!
![image](https://cloud.githubusercontent.com/assets/21232117/25782158/6265660c-3377-11e7-9a2e-5a386bd50ec7.png)

Here's also an example of how it looks like in OBS if it helps!
![image](https://cloud.githubusercontent.com/assets/21232117/25782168/97e376a2-3377-11e7-95f5-badf0ac29acf.png)

Here's also an screenshot of the txt file if it helps! ^^
![image](https://cloud.githubusercontent.com/assets/21232117/25782173/bddf0cfe-3377-11e7-85aa-a3e148211ea7.png)

**Comment by Wykks** [comment]
Hi ! Thanks for the report

I think it's fixed in the next version, which will be release soon (when mozilla wants to validate this addon...)

**Comment by Candy-Sama** [comment]
Ah, I see! Thanks alot for the info! Will await accordingly~

**Comment by Wykks** [comment]
4.2.1 is finally up :)
