### ISSUE TITLE
Youtube New Design

### ISSUE THREAD

**Issue by BLADEkuzia** [Wykks/Untamed-Now-Playing-Next#148]
Hey Hey, great job with this plugin. I just want to inform you that the plugin does not work with the new YouTube design. (included is only through trial mode) But if you return the old design the plugin works perfectly!

**Comment by Senpos** [comment]
Once it will release officially, we'll take a look, but for now i'd recommend to use old design.

**Comment by BLADEkuzia** [comment]
Well new desing officially release, what you think?

**Comment by Senpos** [comment]
More information about new YouTube design here: https://github.com/Wykks/Untamed-Now-Playing-Next/issues/165#issuecomment-334986253
