### ISSUE TITLE
UNP fails to fetch information from SoundCloud & Spotify

### ISSUE THREAD

**Issue by Reddosan** [Wykks/Untamed-Now-Playing-Next#155]
Hi,

It used to work well back in older versions of both 4.0.0 and Firefox 49. But not I reformatted and installed all the updated versions of UNP 4.2.1 and Firefox 54.0.

It works well with YouTube for instance if I try, it fetches the photo and titles just like I tell it to. I close the tab open a new whether in Spotify or SoundCloud, but the files doesn't get created instantly. When I close the tab the files gets created empty. I open the tab again, but no matter what I try, it doesn't fetch the titles, the files remain empty. I confirm again by opening a YouTube tab, and I see YouTube has no problems whatsoever.

Hope there are any hints you may give me. Or did something become different and I have to do anything now before I can work with SoundCloud and Spotify?

Thanks for your work and support.

-Ray

**Comment by Senpos** [comment]
It is a known problem with **Spotify** #145 and fixed already, but not merged yet.
We have to wait till @Wykks  will handle this.

**Comment by Reddosan** [comment]
Thank you for your comment and update. Much appreciate the time and effort put into this. Definitely would hope it fixes both Spotify and SoundCloud altogether.
