### ISSUE TITLE
UNP still doesn't fetch SoundCloud music info

### ISSUE THREAD

**Issue by Reddosan** [Wykks/Untamed-Now-Playing-Next#157]
I had the issue open before when Spotify and SoundCloud wasn't fetching information.

Now that Spotify is fixed, but SoundCloud got totally ignored.

Hope there's an upcoming fix for that. Cheers!

**Comment by Senpos** [comment]
@Reddosan Are you still interested in getting update? Probably will release new version with fix in few days.

**Comment by Reddosan** [comment]
@Senpos I'm definitely looking and keeping an eye out. I almost check for updates everyday I turn the PC on. For now I'm using Spotify on streams. But I miss my SoundCloud overwhelming list.

**Comment by Wykks** [comment]
Sorry I'm late again... I was going to push the fix someday, good timing with the github notification this time :)
Fix push, will release right now
