### ISSUE TITLE
UNP not fetching info from Pandora

### ISSUE THREAD

**Issue by ntaub2010** [Wykks/Untamed-Now-Playing-Next#158]
It works fine with Google Play and YouTube, but it's not recognizing anything playing from Pandora.

**Comment by Wykks** [comment]
Have you tested the version 4.4 ?

**Comment by Senpos** [comment]
Worked for me on the latest release (4.4).

**Comment by Senpos** [comment]
Since it is working for me and no one mentioned any problems for awhile i consider it is no longer actual.
