### ISSUE TITLE
Not writing .jpeg files but .txt is working - music.amazon

### ISSUE THREAD

**Issue by TobyMonster** [Wykks/Untamed-Now-Playing-Next#164]
I've been using the plugin and text file for some time. Just decided to include album art in my OBS and the file is never being updated. Obviously same local user directory as the .txt file, so Firefox permissions shouldn't be causing it. I'm out of ideas. Is this a bug? Firefox 55.0.3 with UNP v4.5

**Comment by TobyMonster** [comment]
add'l info... streaming from music.amazon. I also tried deleting the unp_album_art file and starting up the browser again. It wrote a new file but it won't change from the placeholder image, either.

**Comment by Senpos** [comment]
Unluckily i have no access to that web site, so can't test.
