### ISSUE TITLE
New youtube layout

### ISSUE THREAD

**Issue by iQuickPwnz** [Wykks/Untamed-Now-Playing-Next#165]
Hello,
Since the new YouTube layout is rolling out and more and more people are getting the new layout, could you possibly update the addon to work on the new youtube page?
I would greatly appreciate that.

Thank you,
Kevin

**Comment by Senpos** [comment]
Thanks for creating an issue.

I have added support for _new YouTube design_, but not merged it yet, so when @Wykks will update extension for the last time - he will be able to check it out. Once official version of extension will release - you will see it here, on GitHub or even on Mozilla's extension page.

For now, if you are interested in using extension **with** new YouTube design support, i can suggest you installing unofficial version of extension, which you can **[download here](https://drive.google.com/uc?id=0B6HBCntn0EZReHBGclpsMGdDcGc)**.

The problem with unofficial (_unsigned_) extension is that you have to install it every time you open your browser. But solution is using **[Firefox Developer Edition](https://www.mozilla.org/ru/firefox/developer/)**, which is kind of normal Firefox with some things for developers, but the killer feature might be opportunity to install even unsigned extensions without headache.

So, here are instructions how to get all the pieces to work:
1. Install [Firefox Developer Edition](https://www.mozilla.org/ru/firefox/developer/)
2. Open it, go to the `about:config`, accept to the things described in that window
3. Find `xpinstall.signatures.required` entry through the search field and set **False** by double-clicking on it
4. Open **Add-ons** page in your browser, go to **Extensions** tab and simply _drag-and-drop_ desired extension right there. No annoying things will happen again.

Please, let me know if this will help.

**Comment by Senpos** [comment]
Thanks for creating an issue.

I have added support for _new YouTube design_, but not merged it yet, so when @Wykks will update extension for the last time - he will be able to check it out. Once official version of extension will release - you will see it here, on GitHub or even on Mozilla's extension page.

For now, if you are interested in using extension **with** new YouTube design support, i can suggest you installing unofficial version of extension, which you can **[download here](https://drive.google.com/uc?id=0B6HBCntn0EZReHBGclpsMGdDcGc)**.

The problem with unofficial (_unsigned_) extension is that you have to install it every time you open your browser. Good thing is all your settings will stay even after restarting a browser. 

If you don't know, how to install unsiged extension to your Firefox -[ here is a short video instruction](https://drive.google.com/uc?id=0B6HBCntn0EZRM3NVSzEyZjZ3SlE).

Please, let me know if this helps.

**Comment by iQuickPwnz** [comment]
@Senpos 

Thank you for your reply. This temporary unofficial extension seems to work on the normal firefox. 
I would like to add that I've found a bug with this extension:

The title text gets correctly put in the unp text file.
However, the album art is not from the current song. The album art in the unp folder always shows the album art of the next song. The song thats next in the YouTube queue, auto play.

I hope I informed you enough with this bug feedback and you now where to look to implement a fix for the album art.

Everything else is working completely fine. I hope this new YouTube fix gets soon implemented in the official version of Untamed by @Wykks .

Thanks,
Kevin

**Comment by Senpos** [comment]
@iQuickPwnz Fixed. Download new version of unsigned extension from my previous comment, i updated the link. 

It seems to [work](https://i.imgur.com/qpoTpmC.jpg) for me.

**Comment by iQuickPwnz** [comment]
@Senpos 

Yes, thank you. This works perfectly with the new YouTube version/layout. Ill be waiting for the offical signed extension version support.

Thanks again,
Kevin

**Comment by Senpos** [comment]
@iQuickPwnz You can find more information about plans on FF57 on this repository [README](https://github.com/Wykks/Untamed-Now-Playing-Next/blob/master/README.md). 

**Long story short:** if extension will be highly in demand by users and @Wykks will have enough time - probably something will see the world some day :)
