### ISSUE TITLE
di.fm

### ISSUE THREAD

**Issue by StarBurstx** [Wykks/Untamed-Now-Playing-Next#167]
Hi! Dont working "di.fm" parsing... Maybe i am one of a kind with this problem....

**Comment by Senpos** [comment]
Thanks for creating an issue.

I have fixed support for **di.fm**, but not merged it yet, so when @Wykks will update extension for the last time - he will be able to check it out. Once official version of extension will release - you will see it here, on GitHub or even on Mozilla's extension page.

For now, if you are interested in using extension with fixed **di.fm** support, i can suggest you installing unsigned version of extension, which you can **[download here [ver. "di.fm" from 11.10.2017]](https://drive.google.com/uc?id=0B6HBCntn0EZReW9ZcEp4ME5XLWc)**.

The problem with unofficial (_unsigned_) extension is that you have to install it every time you open your browser. Good thing is all your settings will stay even after restarting a browser. 

If you don't know, how to install unsiged extension to your Firefox -[ here is a short video instruction](https://drive.google.com/uc?id=0B6HBCntn0EZRM3NVSzEyZjZ3SlE).

Please, let me know if this helps.
