### ISSUE TITLE
Spotify Artist Name Spacing

### ISSUE THREAD

**Issue by SrirachaSweat** [Wykks/Untamed-Now-Playing-Next#170]
Everything works fine with OBS and Spotify Web Player besides a lack of space in between artist names. The names just get merged together, omitting any punctuation, so that "Artist A" & "Artist B" would appear as "Artist AArtist B" in the field.

**Comment by Senpos** [comment]
Can you provide a link to a song where problem appears?

**Comment by SrirachaSweat** [comment]
Link: https://open.spotify.com/track/59i2ycqIZG1Z7sTbW8Mt8n

Here is an example with two featured artists on the track. So, instead of displaying the track as  "Artist A, Artist B, Artist C" like on Spotify, it's appearing as "ArtistAArtistBArtistC ".

**Comment by Senpos** [comment]
@SrirachaSweat
I think it will work properly now.

Changes are only avaliable in repository for now, so if you want to get extension with the latest changes including fix of your problem - you might want to build it by your own.

To simplify things for you, i've built extension from Git, so you can download unsigned version of it [here](https://drive.google.com/uc?id=0B6HBCntn0EZRYUJDMXJzMFhNTDA).

The problem with _unsigned_ extension is that you have to install it every time you open your browser. Good thing is all your settings will stay even after restarting a browser. 

If you don't know, how to install unsiged extension to your Firefox - [ here is a short video instruction](https://drive.google.com/uc?id=0B6HBCntn0EZRM3NVSzEyZjZ3SlE).

Please, let me know if this helps.

**Comment by Senpos** [comment]
@SrirachaSweat Is your problem solved?

**Comment by SrirachaSweat** [comment]
@Senpos, I tried loading the temporary extension to check out, but it just gives me this message when I try to launch UNP from the toolbar.

"Access to the file was denied The file at resource://jid1-ccxbupa5pamtyw-at-jetpack/data/common/options/index.html is not readable. It may have been removed, moved, or file permissions may be preventing access."

**Comment by Senpos** [comment]
@SrirachaSweat 
Can you tell me what version of Firefox do you use? 
Did you try to remove old extensions, restart browser and then load extension i've attached?

**Comment by SrirachaSweat** [comment]
@Senpos Yes, tried the above and did not launch for me. I'm on 56.0.1

**Comment by Senpos** [comment]
@SrirachaSweat 
Did you try to disable all extensions, restart browser, then install UNP?
I've built UNP again, so you can try this: [https://drive.google.com/uc?id=0B6HBCntn0EZRQkVBLTZ0RVl1RFk](DOWNLOAD)
