### ISSUE TITLE
Writing Info to separate text files

### ISSUE THREAD

**Issue by SrirachaSweat** [Wykks/Untamed-Now-Playing-Next#171]
Would be really helpful for layout design purposes if there was an option to pull the artist info and song info into separate text files to read from.

**Comment by Senpos** [comment]
Hey there, i think it is kind of useful, but i doubt that this feature will see the world in the near future.

If you are not familiar yet with the current situation of extension, consider reading this repository [README](https://github.com/Wykks/Untamed-Now-Playing-Next/blob/master/README.md).

I hope, when @Wykks will have time to implement new version of extension for FF57+, he might try to make this happen, but for now, i am only supporting proper work of sites, so unfortunetly this enhancement will wait for better time.

**Comment by Gamerbiomek2** [comment]
I would love the custom text to written to album, artist and track and not just the now playing file
that would be nice
