### ISSUE TITLE
Update to Quantum?

### ISSUE THREAD

**Issue by morkthedork** [Wykks/Untamed-Now-Playing-Next#173]
This is still a legacy addon, are the devs able to update this to firefox build 57+? Or can we just do this on our own?

**Comment by Wykks** [comment]
https://github.com/Wykks/Untamed-Now-Playing-Next#important-information :)

**Comment by Wykks** [comment]
Closing as duplicate of https://github.com/Wykks/Untamed-Now-Playing-Next/issues/142
