### ISSUE TITLE
No File Being Created

### ISSUE THREAD

**Issue by CatalystOnTV** [Wykks/Untamed-Now-Playing-Next#177]
When I input the directory where I want the file, I had mine put into a file named UNP in my Documents, It didn't do anything. One attempt, a file was made, but when I made a source to read that txt file on OBS and I played a song on YouTube, I said nothing. I've tried reinstalling and giving admin privilages to FireFox, I just can't find the solution.

**Comment by Senpos** [comment]
- What version of Firefox do you use?
- What version of extension do you use?
