### ISSUE TITLE
Support for jazzradio.com classicalradio.com rockradio.com

### ISSUE THREAD

**Issue by jevanpipitone** [Wykks/Untamed-Now-Playing-Next#179]
Support for jazzradio.com classicalradio.com rockradio.com ; the main one I'm interested in is jazzradio.com since I like using that one. These are all part of the di.fm premium network see https://www.di.fm/premium

**Comment by Senpos** [comment]
@jevanpipitone 
Hi there,

Support for these services is already merged to master, so you can build extension as described in README.

I will build and publish new release with these changes included once we will be done with Pull Requests. 

If you don't want to bother with building extension on your own, you can wait and i will notify you here once it will be done.

**Comment by Senpos** [comment]
@jevanpipitone
Released: https://github.com/Wykks/Untamed-Now-Playing-Next/releases/tag/4.7
