### ISSUE TITLE
There's no text file made.

### ISSUE THREAD

**Issue by gwennshinguji** [Wykks/Untamed-Now-Playing-Next#187]
Here are my options: https://imgur.com/CA9hhRU.png

No text file is made when a song is played in the folder I set it to.
I've tried playing from YouTube, Spotify, and SoundCloud.

**Comment by Senpos** [comment]
Hi,

What browser (and version) do you use?
I have not tested this extension on *nix for a while, so this may be the reason why this does not work.

**Comment by gwennshinguji** [comment]
Sorry, I forgot I made this thread.

It appears to try to make its own directory every time I make a directory for the file. For example, if I set the file to be in "~/Documents/music" it will put the file in "~/Home/(user)/Documents/music" as if that were the home directory. Setting it to just be "/Documents/music/" doesn't seem to work either. I've given up on using this, I'll just work around it.
