### ISSUE TITLE
Support for Synchtube URLs

### ISSUE THREAD

**Issue by Ditsypop** [Wykks/Untamed-Now-Playing-Next#22]
Synchtube uses youtube to play videos. An example can be found at http://synchtu.be/r/Playhouse

Sometimes the URL (if this program works that way) will have a hashmark at the end such as http://synchtu.be/r/Playhouse#

Since youtube is what the songs play from I presume it shouldn't be too difficult to incorporate.

**Comment by Wykks** [comment]
Fixed in 2.1
