### ISSUE TITLE
Adding "Ultra Radio"

### ISSUE THREAD

**Issue by Senpos** [Wykks/Untamed-Now-Playing-Next#27]
http://radioultra.ru/player/#ultra
Current track is displayed here: http://radiopleer.com/info/ultra.txt 
Just need to check is music playing now and parse the text file.

**Comment by Niller2005** [comment]
Fixed in my latest update

**Comment by Wykks** [comment]
Hi Niller2005, can I include your work into UNP ?

**Comment by Niller2005** [comment]
Of course

**Comment by Wykks** [comment]
Fixed in 2.1
