### ISSUE TITLE
Google stops pluggin

### ISSUE THREAD

**Issue by sam99lee** [Wykks/Untamed-Now-Playing-Next#30]
so guys Chrome stop the pluggin for a malware or virus protect, but what i think that should happen is that you guys could release untamed now playing next on chrome webstore... soo that we all can listen to any supported music and know what is it for any streaming software. I am a twitch.tv streamer who wants to so my stream what songs are playing so please get back to me as soo as possible. I think that we all would like to have this program up and running again

**Comment by Wykks** [comment]
Yep, I definitely would do that... If Google wasn't deprecating NPAPI which broke UNPN :(
See #7
