### ISSUE TITLE
Uncaught TypeError: plugin.isDirectory is not a function

### ISSUE THREAD

**Issue by demonicpagan** [Wykks/Untamed-Now-Playing-Next#35]
I've just recently gone about readding this extension back to Chrome for my streaming purposes and am encountering this error: 

Uncaught TypeError: plugin.isDirectory is not a function

The following is what I'm using for my save location: C:\Users\Dustin\Desktop\Streaming\unp\

When I click save is when I notice this error. I am using the UNPNP_v1.4.crx file. I've reviewed and made sure I have my permissions set that I had as a fix for an error affecting the same line of code.

options.js:313 - #12 but that hasn't cleared the issue up.

I think the fact I can't save my setting for my save directory is extending out to another error I receive. I can't say for certain until this one is resolved.

Version of Chrome: Version 43.0.2351.3 dev-m (64-bit)

**Comment by sam99lee** [comment]
Yep, nothing is wrong, its chrome. Google are no longer supporting non-google webstore apps, if they are downloaded googe will just block or uninstall it from extensions

**Comment by demonicpagan** [comment]
It is installed w/o any issue except for not being able to save any settings.

**Comment by sam99lee** [comment]
Yes, but google will remove it, in a few hrs or next time u open chrome. But the name has to be unpn, i had the same problem a few months ago

**Comment by demonicpagan** [comment]
I've opened and closed chrome many times tonight. What do you mean the name has to be unpn? I don't understand what you mean.

**Comment by sam99lee** [comment]
Idk y, but unpn means untamed now playing next, that is the title of this project now

**Comment by demonicpagan** [comment]
Yes, I am aware of that the project is.

**Comment by sam99lee** [comment]
If u are still having issues, i have no idea how to fix it, but im hoping that unpn will still live!, cya

**Comment by untamed0** [comment]
I believe this is due to #7, as Chrome has now removed NPAPI support.

**Comment by demonicpagan** [comment]
Well, that is not cool at all. What am I to do now for my "Now Playing"

**Comment by Wykks** [comment]
Port on Firefox ongoing.
Using this : https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm
