### ISSUE TITLE
a quick suggestion 

### ISSUE THREAD

**Issue by sam99lee** [Wykks/Untamed-Now-Playing-Next#36]
Instead of making this for chrome to read and gets deleted on extensions, y not make a program, like a bot that can see what you are listening to from any website that u want to support and it puts the music in a text or other files that a stream or something can see

**Comment by Wykks** [comment]
Yeah I already considered this. But adding an external software doesn't make it easy to install/use.
And there already a program doing this approach (SMG Now playing).
