### ISSUE TITLE
AlbumArt Default Picture

### ISSUE THREAD

**Issue by Kipx** [Wykks/Untamed-Now-Playing-Next#39]
Using Pandora, if you download album art and there is no art, it shows up as a red block (http://puu.sh/hruB9/64d3bbb60b.png).
Would be nice if there could be a default picture for when album art is not detected.

**Comment by Wykks** [comment]
Default picture when no album art is already implemented. Something must be wrong with our Pandora  support (#25 as well).
I can't use pandora easily (doesn't function in my country, but a VPN should works).
@untamed0 can you take a look ?

(It should affect both chrome and firefox version)

**Comment by Niller2005** [comment]
Just tested it works fine for me in firefox.

**Comment by Kipx** [comment]
What does the default album art look like for you? I tried reinstalling it, still comes up as a red box when a song without album art comes on Pandora.

**Comment by untamed0** [comment]
The default album art is http://ipaddr.me/unp/png2jpg.php, I'll look into this issue when I investigate #40 next week (unfortunately I need to use a VPN to check too, which I have but not setup at the moment).

**Comment by Wykks** [comment]
There was some unwanted things (because of iframe). It should works fine now.

**Comment by Wykks** [comment]
#derp , not released yet

**Comment by Wykks** [comment]
Fixed in 2.1
