### ISSUE TITLE
fileSystem api for Chrome

### ISSUE THREAD

**Issue by Wykks** [Wykks/Untamed-Now-Playing-Next#40]
See if we can use this api for Chrome : https://developer.chrome.com/apps/fileSystem

**Comment by Wykks** [comment]
Any news on this @untamed0  ? :)

**Comment by CuGBabyBeaR** [comment]
chrome.fileSystem API only for app, not for extensions.
add "fileSystem" to manifest, it will shows:
'fileSystem' is only allowed for packaged apps, but this is a extension. 

And also, "fileSystemProvider" API works only on Chrome OS.
https://developer.chrome.com/extensions/fileSystemProvider

**Comment by Wykks** [comment]
Hey thanks for the infos !
Soo we need to set the "App type" to "extension" for "Content script" (https://developer.chrome.com/extensions/content_scripts) while we need "Chrome app" (the new packaged app) type for fileSystem...
This "App type" system (https://developer.chrome.com/webstore/choosing#flow) is one of the main reason why I don't like chrome app dev... This is a mess (or I'm too dumb to understand it correctly).

**Comment by CuGBabyBeaR** [comment]
Chrome makes simple problem complex. It is hard to understand and use. I didn't totally figure it out too.

Can packaged app run in the background all the time?
And also, can we make extension communicate with packaged app?

If so, it seems that we can build a packaged app as a service to handle filesystem operations, and keep extension for inject content.js to target pages.

**Comment by Wykks** [comment]
Yep, there's similar research here : https://groups.google.com/a/chromium.org/forum/#!topic/chromium-apps/OATCEIQdemk
(There post are from 2011, hopefully things may have changed...)

Still, it's not clear... I think our best bet is to try to convert UNP in a packaged app and see how things are going... And eventually create a 2nd app for content-script. But I don't know if this https://developer.chrome.com/extensions/messaging can work between packaged app and extensions.

Summary : I have no idea :D

**Comment by CuGBabyBeaR** [comment]
https://developer.chrome.com/apps/tags/webview

Does this means we can open music site in a webview tag and grab info from that page?

**Comment by untamed0** [comment]
Sorry for the delays with this, I've been very busy with other projects and keep meaning to get back to this but haven't had a real chance to do so. Here are my findings so far:

As @CuGBabyBeaR has said, chrome make life as awkward as they can. I originally looked into an app/extension hybrid, using the proxy.js code from the original UNP chrome extension, unfortunately this was depreciated and now, as of June 2015, chrome no longer loads this types of apps. Chrome apps are completely isolated from the DOM so porting UNP would be no good.

However, you can create an app and an extension and use the [chrome.runtime](https://developer.chrome.com/extensions/runtime#method-sendMessage) API to communicate between them, the user would need to install both (might also be able to package them together with an installer exe) but this isn't too much of a workaround.

Another possible option is webview as @CuGBabyBeaR mentioned, but this would involve having the user use the app as a make shift browser, I'm not sure if that's possible but if it is, I don't think it would be as effective or easy to use as the above 1 app 1 extension solution.

**Comment by Wykks** [comment]
Welcome back Sam :D 

About the webview stuff (if its feasible) : 
A streamer is used to setup some stuff before launching his stream, so it's ok for that kind of user I think.
But for other kind of user like rainmeter (or simple notification when it will be available), launching the music website through UNP isn't very handy.

So yeah, I prefer the 2 app solutions. We can specify the link of the other app in the Chrome Web Store. An executable installer may be a bit too much I think, but why not.

If you want to start something, let me know. I'll finalize the abstraction, so this way, the chrome version will be able to use directly contents-scripts inside the website folder. And I think we can then create a new repo for the common part between the two extensions.

**Comment by CuGBabyBeaR** [comment]
An advantage of Extension-App model is that it can save lot of work in reconsitution.

I tried Extension-App model this afternoon. Here are my conclusions so far:
1. Extension can launch app. So we can launch app any time if we want.
2. Extension can communicate with app by runtime.sendMessage . 
3. App can save message from extension to in specific text files successfully.

Here are my problems now:
1. How to insure app runs in single-instance model?
2. Can extension install app automatically?

If you guys want code-review please let me know.

**Comment by Wykks** [comment]
Well done, that's encouraging !
1. Unfortunately, I have no idea (yeah, again..). But with runtime.sendMessage, these things could  eventually be detected, no ?
2. As far I know, Chrome tends to avoid any installation outside their Web Store (I'm not even sure if an external installer can do that today). So I doubt an extension can be installer automatically... But when the app is installed, showing something like a big red link to the extension should be fine I think :D

**Comment by CuGBabyBeaR** [comment]
Here are the things.

`chrome.fileSystem` API can write files not by path, but by` Entry`, which is a Object containing encrypted path information. `Entry` only can created by [chrome.fileSystem.chooseEntry() method](https://developer.chrome.com/apps/fileSystem#method-chooseEntry), which work only in a window created by app. 
But app can run in multi-instance model. If multiple instances running, send a message to app, it will create multiple windows with "Choose Path" button. That is not good.

Is there any good idea?

**Comment by untamed0** [comment]
@Wykks We'd be using the chrome.runtime API how it's intended. However, knowing Chrome it could be removed/depreciated at any time, but so could any workaround we find. I agree, I highly doubt we'd be able to install the app/extension together through Chrome or the webstore, Chrome are quite clear about them remaining separate (after the removal of legacy packaged apps). Also just looked into a installer exe; before you could install an extension from an exe if the extension was published in the webstore, but it looks like that has now been depreciated too.

@CuGBabyBeaR I'd like to see what code you have so far if possible. Can we use the App to set the configuration options, then store the encrypted path? Then call the app with chrome.runtime every time there is data to be written, and after the data is written close the app? This would solve the issue of single instance.

**Comment by CuGBabyBeaR** [comment]
I publish a repo of my code.
https://github.com/CuGBabyBeaR/UNPPlayground


App can save `Entry` by its  `entryId` which is a String can get by `chrome.fileSystem.retainEntry()` method, and then restore by `chrome.fileSystem.restoreEntry()` method.  
And also, `chrome.fileSystem.getDisplayPath()` method can get decrypted path of `Entry`.

But as what [description of App Lifecycle](https://developer.chrome.com/apps/app_lifecycle) says, App can only close by runtime "when the event page has no executing JavaScript, no pending callbacks, and no open windows". It seems that we can not control app lifecycle manually.

Even if we can terminate app manually, I do not think Launch-Write-Terminate model is good. Because we can not ensure extension will launch app and send message to it always after previous  instance is terminated in that model. And also, it will take unnecessary system cost.

In my test, it looks that once onMessageExternal listener settled, the app will not closed by runtime. I think we can launch app in callback of sendMessage method if app is not running, and then wait one or half second for app launching and send message again. But I'm considering of the time to wait. If too long, that may affect user experience. If too short, it may cause multiple instances launched on low-performance device.

**Comment by Wykks** [comment]
(Just so you know, I will look your work sooner or later this week. It just take more time to setup than working on the current UNP ^^)

**Comment by Wykks** [comment]
Sorry for the delay, unexpected stuff...
Here's what I got, for now : 

*How to insure app runs in single-instance model?*
About the app lifecycle. Why not launch the App **once**, when the extension start ? I tried in your setup, it works fine.
Better : we can (and should) use chrome.runtime.connect(); to get a Port object. This way, when the extension have the port object, we know the app is launched, and we don't need to launch it again.
If the user manage to launch a new instance of the App (with the launch button in chrome://extensions/), well, we already got a Port of our instance, so our message will only be send to our instance anyway.

*Can extension install app automatically?*
I found this stuff : chrome.webstore.install() and chrome.app.isInstalled()
chrome.webstore.install() prompt the user to install the app, it's better than nothing.

**Comment by CuGBabyBeaR** [comment]
Launch App when extension start is something we should eventually implement. As you noticed, I added a onStartup listener to launch app (and commented it). What I concern about is that what if App accidentally terminated, a pull up action should be executed by extension. But that may lead to launch multiple instance. That is why I was seek a single-instance model.

Send message by port is good, App should use port for communication. That was my bad.

I was engaged in little tasks of my new job, and also I'll go for field work for one month in next week, so at least in next 5 weeks I can't coding any more. After that I'll catch up on you guys.

**Comment by Wykks** [comment]
Okay
Thanks again for helping !

I'll will clean the code and abstract the specifics parts for Firefox, since we now know that we can do something with Chrome (with some limitation but doable).

I have little free time for UNP as well (and I have other projects too) so it will progress slowly but surely :)

**Comment by nightfury956** [comment]
hello, i need help i click save and nothing happen

**Comment by Wykks** [comment]
Please see obs forum; this has nothing to do with this issue.

**Comment by Wykks** [comment]
I think going with fileSystem api is not a good idea anymore unfortunately (see #93).
