### ISSUE TITLE
Spotify doesn't work

### ISSUE THREAD

**Issue by youssefdetovernickr** [Wykks/Untamed-Now-Playing-Next#45]
play.spotify.com doesn't work with this extension.

**Comment by Wykks** [comment]
But... but it *should* works !
....
Okay my bad, fixed :)

**Comment by Wykks** [comment]
Just in case you want it now : https://www.dropbox.com/s/va4q249lwfl3b4n/unp_dev.xpi?dl=1

**Comment by youssefdetovernickr** [comment]
Thx my nigga
