### ISSUE TITLE
www.animenfo.com/radio

### ISSUE THREAD

**Issue by ginko147** [Wykks/Untamed-Now-Playing-Next#56]
Please add this website to be supported by your plugin.
I tried to add it by myself but I have some problems adding the song name and album art.
Thanks!

**Comment by Wykks** [comment]
Whoe this one seems very specific, but since UNP support already this kind of website ; I guess it's ok

**Comment by ginko147** [comment]
Well yea. I'm looking mostly to get the song name, artist and album art link from it, but if you can add more than that will be fine :)
