### ISSUE TITLE
Spotify still doesn't work

### ISSUE THREAD

**Issue by DopaSensei** [Wykks/Untamed-Now-Playing-Next#57]
Hi :D I saw that you fixed this issue on a last ticket, but I reinstalled UNP today (the dropbox link, dev version), and it doesn't deals with Spotify. The text file keeps my last listened track on Soundcloud and that's all :p

Hope it's not something that's happening to me only :p

Your work is amazing tho, continue like that !

**Comment by Wykks** [comment]
Yeah you're right, someone already told me on OBS forum.
I totally forgot to reopen the bug :D 

I thought that just adding player.spotify.com along with play.spotify.com was enough.
But, I figured that player.spotify.com is actually a new web player; and it seems that only some people have access to it. Annnnd, saldy I don't :(

Here, I described how you can help me to try adding support of player.spotif.com : 
https://obsproject.com/forum/threads/unp-now-playing-pandora-youtube-lastfm-spotify-web-only-31more.12633/page-6#post-149281

Thanks !

**Comment by DopaSensei** [comment]
Hello :)

Here's the code while music is playing : https://zerobin.net/?4989d0cdc4e2ff4f#EU9BlpzvuG5TgpVoujfgEuLPt+PrNDMmIVnX06i1VJE=

And when music is paused : https://zerobin.net/?f1e93171780cc1a3#E6awIYJDR7UMBpvkThLE40fP+WTdwvJCzeQbaPjgeJ0=

I've got the Hola extension, so I guess it may have messed up with the code, tell me if you want some code w/o this extension.

Cheers :)

**Comment by Wykks** [comment]
Well, same remark as https://obsproject.com/forum/threads/unp-now-playing-pandora-youtube-lastfm-spotify-web-only-31more.12633/page-6#post-149368
*Did you just done a right clic "View Page Source" ? Because it seems to be only the raw page, not proceeded by javascript. I can't do anything with that :D*

**Comment by DopaSensei** [comment]
Mate, I just pressed F12, and right-clicked on the HTML balise, selected "Copy Outer HTML", and that's what I got : https://zerobin.net/?c4f4dff8d66a119e#Yq8AFY9EO2EV5Anje7dF90Kj/PSEoUqqTGhH+0d0sRs=

**Comment by DopaSensei** [comment]
Well, I can share my account with you if it allows you to use the player.spotify website, there's no problem about it :p

**Comment by Wykks** [comment]
Oh okay, it's caused by the iframe stuff. My bad.
If you can share your account, yeah that would be very very usefull :D
You can send your access here : contact [at] wykks.eu
Thanks !

**Comment by Wykks** [comment]
Got it ! Working on it, thanks again :D

**Comment by DopaSensei** [comment]
No problem :)

**Comment by Wykks** [comment]
Wanted to listen change with DOM Mutation Observer (which means instant change in text file) but I'm not familiar enough with it (and a bit trickier to debug with Iframe stuff).
Anyway, it's done, finally :D

**Comment by ArchonFreak** [comment]
Please release it!
Thanks for UNP :)

**Comment by DopaSensei** [comment]
Thanks for your amazing job mate :) :dancer:

**Comment by Wykks** [comment]
Sorry for the delay, it's up ! :)
