### ISSUE TITLE
Spotify is broken... Again

### ISSUE THREAD

**Issue by Wykks** [Wykks/Untamed-Now-Playing-Next#63]
Seems like the new player of spotify changed again. (https://obsproject.com/forum/threads/unp-now-playing-pandora-youtube-lastfm-spotify-web-only-31more.12633/page-7#post-156475)
@DopaSensei can you confirm ? :)

**Comment by DopaSensei** [comment]
Wow just came back to your repo and notified this :') gonna check it out soon :)

**Comment by DopaSensei** [comment]
Well w/ my account, spotify player didn't changed, I mean in terms of design. Didn't looked at the code, i'm not an expert :} . You still have my IDs anyways, I didn't changed them. Feel free to use my account for testing/chillin' purpose.

**Comment by Wykks** [comment]
Okay thanks :)

(I'm really busy these days.... If someone really want this fixed asap, let me now :))
