### ISSUE TITLE
UNP does not load data anymore for google play (Firefox version 41.0.2)

### ISSUE THREAD

**Issue by BradMcDev** [Wykks/Untamed-Now-Playing-Next#68]
2 weeks ago this was working fine; I'm guessing some change in 41.0.2 (or the way Google Play is passing data?) changed?

I changed nothing about my UNP add-on & like I said it was working 2 weeks ago with zero changes since then aside from whatever FF updates ran when I started the browser. See attached images for my settings, the 0 byte files written to my drive, and my installed add-ons & extensions. Tried re-installing add-on multiple times, including old versions. Nothing works.

![unp_settings](https://cloud.githubusercontent.com/assets/3528774/10710919/7121bd38-7a39-11e5-8134-d65876d30b35.png)

![unp_files](https://cloud.githubusercontent.com/assets/3528774/10710927/9ee89854-7a39-11e5-8d34-1b964b5a99de.png)

**Comment by Wykks** [comment]
Hi !
Thanks for your report, something must have changed with google play. I'll fix it right away !
