### ISSUE TITLE
Plugin no longer working / NPAPI deprecation

### ISSUE THREAD

**Issue by Zenjaa** [Wykks/Untamed-Now-Playing-Next#7]
Chrome will now only install extensions from Google’s Web Store and deactivates all other installed extensions.

**Comment by Wykks** [comment]
Port on Firefox ongoing.
Using this : https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm

**Comment by untamed0** [comment]
I recently discovered a new API which we might be able to use for Chrome - https://developer.chrome.com/apps/fileSystem I haven't had a chance to experiment with it yet though

**Comment by Wykks** [comment]
Oh well.. It doesn't seem easy to use nonetheless.
I'll look into it, maybe, someday (you know me haha)
By the way, the Firefox port is almost ready !

**Comment by faeton** [comment]
No news on this?
Maybe Chrome for devs "unpacked extension" version?

**Comment by Wykks** [comment]
See #40 
I just finished to separate the website support logic as one file per website. It make it easier to maintain, and it could be directly used by a chrome version eventually.
@untamed0 said that he was going to look into this chrome API but it seems it doesn't want to do it anymore (It's ok, he don't *have to* do it).
I don't feel like to do that stuff *for now* too. I prefer the sdk of Firefox than Chrome.

(I hope my sentences makes senses, I'm not sure about the grammar :D)
