### ISSUE TITLE
8tracks Doesn't Seem to Be Working!

### ISSUE THREAD

**Issue by gr0wlithee** [Wykks/Untamed-Now-Playing-Next#70]
First off, I love this project! It's really helpful! I want to use this with 8tracks but it doesn't seem to be working. It is however working with other sites like Pandora,etc. ( I tested)

Just wanted to bring it to your attention!

**Comment by Wykks** [comment]
Thank for your report !

I'll fix that asap :)

**Comment by Wykks** [comment]
Aand fixed !
But for now the album picture won't work because the picture conversion system is not working (#54)

**Comment by gr0wlithee** [comment]
Everything is working perfect now! Thanks for being speedy!!! :D
