### ISSUE TITLE
Unable to save settings and issues with preference page

### ISSUE THREAD

**Issue by Fooughhy** [Wykks/Untamed-Now-Playing-Next#76]
Hello!

So I'm just trying to put the currently playing song in Google Play Music in OBS but having some issues with this one (no others have worked at all).

My "preferences" page looks like this when I click the extension-button in Firefox: ![unp](https://cloud.githubusercontent.com/assets/6977416/12080450/beb9ba1a-b25a-11e5-967e-1b0ef61f2ac2.png)

All text is like placeholder text and completely useless. I am guessing that the top field is for where the file is supposed to be saved, but I am unable to change the "USERNAME" to my username on my PC since it won't save when I click "Save".

Fresh install of firefox (I've only changed a thing in about:config to allow me to install your unreviewed version of UNP).

**Comment by Wykks** [comment]
um that's weird, it look like angular was successfully loaded but didn't manage to load the translation.
Never happened to me before.

Does this happen with the latest version ? https://addons.mozilla.org/en-US/firefox/addon/untamed-now-playing/versions/?page=1#version-3.0.0 (published 3 hours ago)

**Comment by Fooughhy** [comment]
Yupp, I installed 3.0.0 (file is called "unp-3.0.xpi").

**Comment by Wykks** [comment]
Okay I must have messed up the translation config (bad failback or something like that).
Thanks you for the report ! I'll fix that tonight
