### ISSUE TITLE
Pandora doesnt work :/

### ISSUE THREAD

**Issue by Cr0ssF1r3x** [Wykks/Untamed-Now-Playing-Next#79]
Pandora all of a sudden stopped working. I think it was on the last update. Please fix soon!

**Comment by Canhascow** [comment]
How do I install this fix?

**Comment by Wykks** [comment]
There is a "how to" inside the REAME.
Also, you can use the older version https://addons.mozilla.org/en-US/firefox/addon/untamed-now-playing/versions/. 2.8.1 should works fine with pandora.
Or wait for the next release :)
