### ISSUE TITLE
Ver 3.0.2 Completely unusable in Firefox 44.0b9 (ver 2.8.1 works fine)

### ISSUE THREAD

**Issue by danielsangeo** [Wykks/Untamed-Now-Playing-Next#81]
Not sure what's causing this but I cannot set any options because there's no visible text--just the info buttons and they don't work.  Thanks!
![unp-resurrection](https://cloud.githubusercontent.com/assets/16742372/12376906/fef78b20-bcbe-11e5-8e4f-908b39023b2f.jpg)

More info: Windows 10 Home, 64-bit, also happens with uBlock disabled

**Comment by Wykks** [comment]
Interesting, I'll see what's wrong with FF 44
Thanks for the report :)
