### ISSUE TITLE
Pandora doesn't work in latest version

### ISSUE THREAD

**Issue by derektheish** [Wykks/Untamed-Now-Playing-Next#82]
I was using 3.0.2 and pandora wasn't working at all. It worked for google play and a couple other sites. I was also having issues where if I clicked "Saved" on the options page it wouldn't show the saved changes if you went back to the options page later, but if you restarted firefox it would show it correct. 

Also it wouldn't save the extra spaces in the "Plain text now playing format" field.

Anyone else who's have the same issues, reverting back to 2.8 (you can get from the https://github.com/Wykks/Untamed-Now-Playing-Next/releases) fixed all these issues for me.

If it makes any difference I'm on firefox 43.0.4

Thanks

**Comment by Wykks** [comment]
Thanks for reporting these issues.
About pandora, I already fixed it. Since it's the third issue about it (#79 #80), I think I will do a release very soon :o 

I leave this open for the other issues mentioned.

**Comment by derektheish** [comment]
Ah, didn't know to look into the 'Closed' issue section, still new to GitHub. 

I turned off autoupdates for now, but look forward to next version :)
