### ISSUE TITLE
beta.nightbot.tv support

### ISSUE THREAD

**Issue by Wykks** [Wykks/Untamed-Now-Playing-Next#85]
https://obsproject.com/forum/threads/unp-now-playing-pandora-youtube-lastfm-spotify-web-only-31more.12633/page-8#post-187894

**Comment by kiezkickerde** [comment]
Needs a fix again. Works great on youtube direct, but not changing anything in the file if the video is played on beta.nightbot.tv (I am still using %s%) in the songrequest - player.

**Comment by Wykks** [comment]
Yes, it's still not implemented for now
