### ISSUE TITLE
New line variable (%n%) not working

### ISSUE THREAD

**Issue by DaanW1991** [Wykks/Untamed-Now-Playing-Next#86]
Some background info:
I'm using UNP to write track data from Youtube to a .txt file. I then use an exterior .ini file to load the track data as variables, to use in a custom visualiser skin for my desktop.
The one big problem here is that the %n% variable does not open a new line; so it just writes the data on one long line (making it unreadable in the .ini file).

Now i'm sure there is some way for me to work around this, but shouldn't the %n% variable be doing it's job? It would sure make my life a whole lot easier.

**Comment by Wykks** [comment]
Works for me. It's probably because I don't add the \r (windows specific) char.

**Comment by Wykks** [comment]
Should be fine now :)

**Comment by DaanW1991** [comment]
Just checked; the error was probably not in the code after all but in my choice of program to check it. Regular notepad still shows one long line of text, but Notepad++ knows better. Thanks for looking into it anyway!
