### ISSUE TITLE
Youtube TV broken

### ISSUE THREAD

**Issue by no-paj** [Wykks/Untamed-Now-Playing-Next#87]
Hi,
the youtube TV thing broke again.

**Comment by no-paj** [comment]
Didn't saw the fix commit, my bad.

**Comment by no-paj** [comment]
Actually still doesn't work. I git cloned and build the xpi. Youtube TV doesn't work.

**Comment by no-paj** [comment]
Nevermind, downloaded the last xpi, worked fine.

**Comment by Wykks** [comment]
Sorry about this !
I really need to improve my release process...
BTW youtube.com (+ tv version) is now auto tested here https://github.com/Wykks/UNP-tests :)
