### ISSUE TITLE
Installation Blocked By Firefox 45.0.1, Error: Add-On Not Verified

### ISSUE THREAD

**Issue by Firedingo** [Wykks/Untamed-Now-Playing-Next#91]
Seems Mozilla added a checking function to new versions of Firefox to prevent malicious add-ons. The downside is anything not signed by them can now not be installed unless additional work is done by the user.
While I understand what Mozilla did, it is likely to cause a range of issues for people trying to install add-ons from 3rd party sites that are legitimate but may not have been validated by Mozilla themselves. Not sure what if anything a developer can do.

**Comment by Wykks** [comment]
I am aware of that.
UNP is actually signed right there :  https://addons.mozilla.org/en-US/firefox/addon/untamed-now-playing/

When you build or use the xpi in the release tabs, you have to set "xpinstall.signatures.required" to false as explained here : https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_(jpm)#Packaging_the_add-on

I should be able to post signed XPI in the release tab though.

**Comment by Wykks** [comment]
I'll now try to post signed XPI in the release page
