### ISSUE TITLE
Possible Soundcloud and Youtube improvements

### ISSUE THREAD

**Issue by Disputes** [Wykks/Untamed-Now-Playing-Next#95]
loving this extention so here are some possible improvements assuming its possible

If no author is detected on the music playing it should use the channel name. Example Bob uploads his music as "ThisMusic" not "Bob - ThisMusic" because the addon cant retrive the author from the title it could try the channel name

with youtube some music channles put the type of music at the start (monstercat will use [Chill] [DnB] [Electronnic]) maybe there could be a tag that exclude certain words so when the song name is saved to the file it does not contain the prefix/suffix some channels add

**Comment by Wykks** [comment]
Hi !

1) Why not, it should be easy to do :)

2) I can add a custom exclude words list option, noted !

**Comment by Disputes** [comment]
thanks! finding this plugin amazing with my rainmeter wallpaper

**Comment by Wykks** [comment]
Some news !
1) Done, if no artist is found, it now get the channel name.
2) Instead of a custom exclude words list, I've reworked the way the artist and title is parsed.

Please tell me if something doesn't look good ! :)

**Comment by Disputes** [comment]
Awesome going to try it out

**Comment by Disputes** [comment]
I have done a pull request that contain some changes to the bracket removal as you probably have better features to add than this. 

thanks
