### ISSUE TITLE
Options page doesn't show in Waterfox

### ISSUE THREAD

**Issue by redsaph** [Wykks/Untamed-Now-Playing-Next#97]
I've been using Waterfox with UNP and when I press the Options in the add-ons page for it, nothing shows. I've included a screenshot of the problem. I also can't see the music note thing near the address bar.

![Image](https://cloud.githubusercontent.com/assets/18696835/15665551/504c56c4-273e-11e6-9319-cb44fc1a95cc.png)

**Comment by Wykks** [comment]
Never tried Waterfox.
Seems like angular doesn't load for some reason.
Since Waterfox doesn't support linux, it will take me a bit more time to figure this out.
Do you have any error in the console ? (usually opened with F12)

**Comment by redsaph** [comment]
Hi, sorry for the late reply. There's nothing in the console.

**Comment by Wykks** [comment]
Just tested in a fresh install of Waterfox (47.0), everything is OK.
Make sure you have the lastest version of UNP and Waterfox.
